### ISSUE TITLE
RESTful API wrapper

### ISSUE THREAD

**Issue by alexpinsky** [mamlukishay/hypr#1]
https://github.com/mamlukishay/hypr/blob/f85ee9e0d0b3df48de0376b171ecf11234ebafb2/profile_pictures/views.py#L6

I would build a nicer wrapper for REST calls to map HTTP methods to ctrl actions. If time doesn't allow, use an ActionFactory to return the specific action you want to perform:

```ruby
def index
  action = ActionFactory.get_action_for request
  result = action.run

  if result.success?
    render json: result.presenter
  else
    head :bad_request
  end
end


class ActionFactory
  def self.get_action_for(request)
     if request.post?
        # return the create action
     else
        # return the index action
     end
  end
end
```

It shows you know your way around design patterns. There's a lot overhead, but they requested you to show your design abilities.

**Comment by mamlukishay** [comment]
Good point - I’ll think about it
