### ISSUE TITLE
where are your tests?

### ISSUE THREAD

**Issue by alexpinsky** [mamlukishay/hypr#2]

**Comment by alexpinsky** [comment]
https://github.com/mamlukishay/hypr/blob/f85ee9e0d0b3df48de0376b171ecf11234ebafb2/profile_pictures/tests.py#L1

**Comment by mamlukishay** [comment]
Good question- I don’t think it’s part of the assignment and that’s my border when coming to implement this in a new language, which already consumed me a lot of time. 
But I guess I should delete all the irrelevant files, including the ones for tests.
