### ISSUE TITLE
Coupled to twitter

### ISSUE THREAD

**Issue by alexpinsky** [mamlukishay/hypr#3]
https://github.com/mamlukishay/hypr/blob/f85ee9e0d0b3df48de0376b171ecf11234ebafb2/profile_pictures/interactions/store_profile_pic_for_twitter_handle.py#L9

Your implementation is coupled to twitter. You can build an abstraction around it using Providers - ProfilePicsProvider. Then you can support other services by only implementing them without ever touching existing code. By doing so, you show your SOLID understanding. You get both Single Responsibility and Open/Close.

**Comment by mamlukishay** [comment]
You're right that it's coupled to twitter. I took your idea
